# Generated by Django 4.2.27 on 2025-12-26 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=25)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'atributos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=128)),
                ('imagen', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=25)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'funciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Getatributos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('nivel', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=128)),
                ('atributos', models.CharField(max_length=128)),
                ('id_clase', models.IntegerField()),
            ],
            options={
                'db_table': 'getatributos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Getfunciones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('nivel', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=128)),
                ('funciones', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'getfunciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Herencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'herencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Herenciaf',
            fields=[
                ('hijo', models.CharField(db_column='Hijo', max_length=128, primary_key=True, serialize=False)),
                ('padre', models.CharField(db_column='Padre', max_length=128)),
                ('id_proyecto', models.IntegerField()),
            ],
            options={
                'db_table': 'herenciaf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'log_actividad',
                'managed': True,
            },
        ),
    ]
