# Generated by Django 4.2.27 on 2026-01-31 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_is_active_usuario_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': True},
        ),
    ]
