# Generated by Django 6.0.2 on 2026-04-27 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_proyecto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_usr',
            field=models.ForeignKey(db_column='id_usr', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='lenguaje',
            field=models.CharField(choices=[('java', 'Java'), ('cpp', 'C++ (G++)')], default='java', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_socioeconomico',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio_bajo', 'Medio-Bajo'), ('medio', 'Medio'), ('medio_alto', 'Medio-Alto'), ('alto', 'Alto')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_disponible', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.CASCADE, related_name='examenes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='intentos_examen', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='core.examen')),
            ],
            options={
                'db_table': 'intento_examen',
                'managed': True,
                'unique_together': {('examen', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.examen')),
            ],
            options={
                'db_table': 'pregunta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('letra', models.CharField(max_length=1)),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.pregunta')),
            ],
            options={
                'db_table': 'opcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('intento', models.ForeignKey(db_column='id_intento', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.intentoexamen')),
                ('opcion_elegida', models.ForeignKey(blank=True, db_column='id_opcion_elegida', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.opcion')),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
            ],
            options={
                'db_table': 'respuesta_estudiante',
                'managed': True,
                'unique_together': {('intento', 'pregunta')},
            },
        ),
    ]
